version: '3'
services:
  redis:
    image: redis:5-alpine
    ports:
      - '6370:6379'
  app:
    build:
      context: ./queue-extract/
      dockerfile: Dockerfile
    environment: 
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5001:5000"

